# TODO: need to sync-wave. this should install prior to below resources
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-minio
spec:
  package: xpkg.upbound.io/vshn/provider-minio:v0.4.3

---
apiVersion: minio.crossplane.io/v1
kind: ProviderConfig
metadata:
  name: provider-config-minio
spec:
  credentials:
    apiSecretRef:
      name: minio-configuration
      namespace: minio-tenant-0
    source: InjectedIdentity
  minioURL: http://minio.minio-tenant-0.svc.cluster.local

---
apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  name: test-bucket-02
  namespace: minio-tenant-0
spec:
  forProvider:
    bucketName: test-bucket-02
    region: us-east-1
  providerConfigRef:
    name: provider-config-minio
