---
apiVersion: minio.crossplane.io/v1
kind: ProviderConfig
metadata:
  name: provider-config-minio
spec:
  credentials:
    apiSecretRef:
      name: minio-configuration
      namespace: minio-tenant-0
    source: InjectedIdentity
  minioURL: http://minio.minio-tenant-0.svc.cluster.local

---
apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  name: test-bucket-02
  namespace: minio-tenant-0
spec:
  forProvider:
    bucketName: test-bucket-02
    region: us-east-1
  providerConfigRef:
    name: provider-config-minio

---
apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  name: project-motherduck
  namespace: minio-tenant-0
spec:
  forProvider:
    bucketName: project-motherduck
    region: us-east-1
  providerConfigRef:
    name: provider-config-minio

{{- if eq .Values.secrets_provider "aws" }}
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-config-aws-s3
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds

# example
# ---
# apiVersion: s3.aws.upbound.io/v1beta1
# kind: Bucket
# metadata:
#   name: test-bucket-73a5f1923
# spec:
#   forProvider:
#     region: us-east-1
#   providerConfigRef:
#     name: provider-config-aws-s3
{{- end }}
