apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-admin
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-admin
subjects:
- kind: ServiceAccount
  name: argo-workflow-admin
  namespace: argo
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

