# xpkg.upbound.io/vshn/provider-minio does not have an arm version
{{- if ne .Values.environment "local" }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-minio
spec:
  package: xpkg.upbound.io/vshn/provider-minio:v0.4.3

---
apiVersion: minio.crossplane.io/v1
kind: ProviderConfig
metadata:
  creationTimestamp: null
  name: provider-config
spec:
  credentials:
    apiSecretRef:
      name: minio-configuration
      namespace: minio-tenant-0
    source: InjectedIdentity
  minioURL: http://minio.minio-tenant-0.svc.cluster.local:9000

---
apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  name: test-bucket-02
spec:
  forProvider:
    bucketName: test-bucket-02
    zone: us-east-1
  providerConfigRef:
    name: provider-config
{{- end }}
