apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenants
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo.git
    targetRevision: HEAD
    path: resources/minio-tenants
    kustomize:
      # If you have environment-specific overlays, you can specify them here
      # namePrefix: ${environment}-
      # For example, if you have a 'local' and 'dev' overlay:
      # path: overlays/${environment}
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
