apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.15.1
    chart: connect
    helm:
      parameters:
        - name: operator.create
          value: "true"
        - name: connect.create
          value: "true"
        - name: connect.credentials.token
          value: "YOUR_1PASSWORD_CONNECT_TOKEN"
        - name: connect.credentials.serverURL
          value: "YOUR_1PASSWORD_CONNECT_SERVER_URL"
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
