{{- if eq .Values.environment "local" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 62.1.0
    chart: kube-prometheus-stack

    # repoURL: https://prometheus-community.github.io/helm-charts
    # targetRevision: 25.26.0
    # chart: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  endpoints:
  - port: metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server-metrics
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
  endpoints:
  - port: metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-repo-server-metrics
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  endpoints:
  - port: metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-sm-cluster
  namespace: minio
  labels:
    v1.min.io/tenant: minio
    release: kube-prometheus-stack
spec:
  jobLabel: cluster-job
  endpoints:
  - bearerTokenSecret:
      key: cluster-token
      name: minio-metrics-bearer-tokens
    path: /minio/v2/metrics/cluster
    scheme: https
    port: https-minio
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      v1.min.io/tenant: minio
{{- end }}
