apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-monitors
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo.git
    targetRevision: HEAD
    path: resources/service-monitors
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment }}.yaml
      values: |
        environment: {{ .Values.environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

