apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://apache.github.io/superset
    targetRevision: 0.12.11
    chart: superset
    helm:
      values: |
        extraSecretEnv:
          SUPERSET_SECRET_KEY: 'CLe7VxY2cpZaV+Gnaxy5m/E4RSoH1NcInX4XgIIZ7kU'
        postgresql:
          image:
            tag: "14.12.0-debian-12-r22"
        bootstrapScript: |
          #!/bin/bash
          pip3 install duckdb duckdb-engine
          if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
    # helm:
    #   parameters:
    #     - name: extraSecretEnv.SUPERSET_SECRET_KEY
    #       value: $SUPERSET_SECRET_KEY
    #     - name: postgresql.image.tag
    #       value: "14.12.0-debian-12-r22"
    #   valuesFrom:
    #     - kind: Secret
    #       name: superset-secret-key
    #       targetPath: extraSecretEnv.SUPERSET_SECRET_KEY
    #       key: SUPERSET_SECRET_KEY
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
