# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: cluster-secret-store
# spec:
#   provider:
#     onepassword:
#       connectHost: http://onepassword-connect.1password.svc.cluster.local:8080
#       vaults:
#         k8s: 1
#       auth:
#         secretRef:
#           connectTokenSecretRef:
#             namespace: 1password
#             name: onepassword-token
#             key: token

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credential
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: aws-credential
            key: aws_secret_access_key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare-operator-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: K8S/Local/Cloudflare

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # name: minio-console-user-credential
  # name: minio-storage-configuration
  name: minio-configuration
  namespace: minio-tenant-0
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: K8S/Local/MinIO

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset-secret-key
  namespace: superset
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: K8S/Local/Superset
