apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.1password.svc.cluster.local
      vaults:
        k8s: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            namespace: 1password
            name: onepassword-token
            key: token
