secrets:
  existingSecret:
    name: enabled
tenant:
  name: minio-tenant-0
  namespace: minio-tenant-0
  configuration:
    name: minio-env-configuration
  pools:
    - name: pool-0
      servers: 1
  configSecret:
    name: minio-env-configuration
    accessKey: minio
    secretKey: minio123
