apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant-0
  namespace: minio-tenant-0
spec:
  secrets:
    name: myminio-env-configuration
    accessKey: minio
    secretKey: minio123
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 2
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  # credsSecret:
  #   name: minio-creds-secret
  image: minio/minio:RELEASE.2023-05-27T05-56-19Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  requestAutoCert: true
