apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo.git
    targetRevision: HEAD
    path: system/cert-issuers
    helm:
      values: |
        environment: {{ .Values.environment }}
        letsencrypt_email: {{ .Values.letsencrypt_email }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
