apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo
    targetRevision: HEAD
    path: system/crossplane/providers
    helm:
      values: |
        environment: {{ .Values.environment }}
        secrets_provider: {{ .Values.secrets_provider }}
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
