{{- if ne .Values.environment "dev" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenants
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo.git
    targetRevision: feature/external-secrets
    path: system/minio-tenants
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment }}.yaml
      values: |
        environment: {{ .Values.environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant-0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
