apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo
    targetRevision: HEAD
    path: system/mssql-server
    helm:
      values: |
        environment: {{ .Values.environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: mssql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

