{{- if eq .Values.environment "amfaro-dev" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nocodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zekker6/helm-charts.git
    targetRevision: HEAD
    path: charts/apps/nocodb
    helm:
      values: |
        persistence:
          config:
            enabled: true
            type: pvc
            accessMode: ReadWriteOnce
            size: 10Gi
            mountPath: /config
  destination:
    server: https://kubernetes.default.svc
    namespace: nocodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
