{{- if eq .Values.secrets_provider "op" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # naming this with `one` vs `1` to prevent it sorting to the top 🤷
  name: onepassword-connect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.15.1
    chart: connect
    helm:
      parameters:
        - name: operator.create
          value: "true"
        - name: connect.create
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
