apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-items-superset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo.git
    targetRevision: HEAD
    path: system/onepassword-items/superset
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
