apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-stores
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/johnallen3d/argocd-demo.git
    targetRevision: feature/external-secrets
    path: system/secret-stores
    helm:
      values: |
        environment: {{ .Values.environment }}
        secrets_provider: {{ .Values.secrets_provider }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

