apiVersion: v1
kind: Namespace
metadata:
  name: superset

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://apache.github.io/superset
    targetRevision: 0.12.11
    chart: superset
    helm:
      parameters:
        - name: extraEnvRaw[0].name
          value: SUPERSET_SECRET_KEY
        - name: extraEnvRaw[0].valueFrom.secretKeyRef.name
          value: superset-secret-key
        - name: extraEnvRaw[0].valueFrom.secretKeyRef.key
          value: credential
        - name: postgresql.image.tag
          value: "14.12.0-debian-12-r22"
        - name: configOverrides
          value:
            my_override: |
              FEATURE_FLAGS = {
                "DASHBOARD_RBAC": True
              }
        - name: bootstrapScript
          value: |
            #!/bin/bash
            pip3 install duckdb duckdb-engine
            if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
