apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-amfaro-dev-op
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: "\n                      environment: amfaro-dev\n                      secrets_provider: op\n                      letsencrypt_email: \"john@threedogconsulting.com\"\n                    "
    path: system/base
    repoURL: https://github.com/johnallen3d/argocd-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
