apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
spec:
  secretName: minio-tls-secret
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: minio.minio-tenant-0.svc.cluster.local
  dnsNames:
  - minio.minio-tenant-0.svc.cluster.local
