name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up `helm`
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.15.2"

      - name: Set up `yq`
        uses: frenck/action-setup-yq@v1

      - name: Validate Helm Chart
        run: |
          for chart in $(find system -name Chart.yaml -exec dirname {} \;); do
            echo "Linting chart: $chart"
            helm lint $chart
            helm template $chart | yq
          done
