name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "latest"

      - name: Validate Helm Chart
        run: |
          helm lint my-app
          helm template my-app

  validate-argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup ArgoCD Autopilot
        run: |
          curl -L https://github.com/argoproj-labs/argocd-autopilot/releases/latest/download/argocd-autopilot-linux-amd64 -o argocd-autopilot
          chmod +x argocd-autopilot
          sudo mv argocd-autopilot /usr/local/bin/

      - name: Validate ArgoCD Application
        run: |
          argocd-autopilot repo bootstrap --dry-run --app my-app-application.yml
